import { useState } from "react";
import { apiFetch } from "../lib/api";

interface PublishPanelProps {
    uris: string[];
    onCancel: () => void;
    onSuccess: (playlistLink: string) => void;
}

export function PublishPanel({ uris, onCancel, onSuccess }: PublishPanelProps) {
    const [name, setName] = useState("");
    const [description, setDescription] = useState("Generated by Spotify Aggregator");
    const [isPublic, setIsPublic] = useState(false);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handlePublish = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!name.trim()) return;

        try {
            setLoading(true);
            setError(null);

            // Read debug flag from site URL
            const searchParams = new URL(window.location.href).searchParams;
            const isDebug = searchParams.get("debug") === "true";
            const apiBase = import.meta.env.VITE_API_URL || "http://localhost:8787";
            const endpoint = `${apiBase}/api/merge${isDebug ? "?debug=true" : ""}`;

            const res = await apiFetch<{ playlistId: string; success: boolean }>(
                endpoint,
                {
                    method: "POST",
                    body: JSON.stringify({
                        uris,
                        targetPlaylistConfig: {
                            name,
                            description,
                            public: isPublic
                        }
                    })
                }
            );

            if (res.success && res.playlistId) {
                onSuccess(`https://open.spotify.com/playlist/${res.playlistId}`);
            } else {
                setError("Publish returned a non-success response.");
            }
        } catch (err: any) {
            console.error(err);
            setError(err.message || "Failed to publish playlist");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="publish-panel card">
            <h3 style={{ marginBottom: "1rem" }}>Publish Settings</h3>
            {error && <div className="error-text" style={{ marginBottom: "1rem" }}>{error}</div>}

            <form onSubmit={handlePublish} style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>

                <div className="input-group">
                    <label htmlFor="pname">Playlist Name</label>
                    <input
                        id="pname"
                        type="text"
                        required
                        placeholder="e.g. 2024 Ultimate Collection"
                        value={name}
                        onChange={e => setName(e.target.value)}
                    />
                </div>

                <div className="input-group">
                    <label htmlFor="pdesc">Description</label>
                    <input
                        id="pdesc"
                        type="text"
                        value={description}
                        onChange={e => setDescription(e.target.value)}
                    />
                </div>

                <div className="toggle-container" style={{ marginTop: "0.5rem" }}>
                    <label>Privacy</label>
                    <div className="segmented-control">
                        <button
                            type="button"
                            className={`segment ${!isPublic ? "active" : ""}`}
                            onClick={() => setIsPublic(false)}
                        >
                            Private
                        </button>
                        <button
                            type="button"
                            className={`segment ${isPublic ? "active" : ""}`}
                            onClick={() => setIsPublic(true)}
                        >
                            Public
                        </button>
                    </div>
                </div>

                <div className="modal-footer" style={{ borderTop: "none", padding: "1rem 0 0 0", marginTop: "1rem" }}>
                    <button type="button" className="logout-button" onClick={onCancel} disabled={loading}>
                        Back to Preview
                    </button>
                    <button type="submit" className="login-button" disabled={loading || !name.trim()}>
                        {loading ? "Publishing (Do not close)..." : "Publish to Spotify"}
                    </button>
                </div>
            </form>
        </div>
    );
}
